### ISSUE TITLE
Add WQ for Carpal pet

### ISSUE THREAD

**Issue by cremor** [Urtgard/WQAchievements#102]
To get the pet [Carpal](https://www.wowhead.com/npc=173847/carpal) you need to get the item [Animated Ulna](https://www.wowhead.com/item=183111/animated-ulna). This item can be the reward of a WQ.

Some comments on Wowhead mention that they got the item from the WQ [Extra Pieces](https://www.wowhead.com/quest=61867/extra-pieces). But this WQ doesn't always reward that item. So the WQ actually need to reward that item to be considered "interesting".

I don't know if this addon can track WQs based on their reward. But if it can, it would be great to track this.

**Comment by Urtgard** [comment]
In the options you can add rewards you want to track. So you dont have to
wait tilll I implement it.

cremor <notifications@github.com> schrieb am Do., 21. Jan. 2021, 18:14:

**Comment by cremor** [comment]
Ah, good to know. Thanks!
