### ISSUE TITLE
No longer tracking Things Remembered

### ISSUE THREAD

**Issue by KnightRyder002** [Urtgard/WQAchievements#103]
I have 1 person left on my Horde Kyrian Rogue for the achievement [What Bastion Remembered] but WQAchievements stopped telling me when it is up. It still lets me know on my Horde Venthyr Paladin for some reason though.

**Comment by cremor** [comment]
I can confirm this. Right now the WQ with the ID 59705 is up and I'm still missing 2 criterias for the achievement, but the addon doesn't show it.

**Comment by KnightRyder002** [comment]
Only thing I can think of is that it somehow knows which of the 10 it is, and knows I have credit for it the specific one that is up. I have only 1 left to get so I can't test it yet.

**Comment by Urtgard** [comment]
I think I messed up the data for this one.
I added both questIds to the first criteria. So you get only a notification if you miss the first criteria.

Thanks for the report
