### ISSUE TITLE
Add broken isles pet battle WQs for Falcosaur mount quests

### ISSUE THREAD

**Issue by CultistO** [Urtgard/WQAchievements#104]
Maybe scope-creeping, but I would find it extremely useful when planning my WQ runs, if it could let me know which zones have pet-battles, as you need to complete a whopping 24 to complete the following quests for the 4 associated mounts:

Bloodgazer Team Up
Direbeak Team Up
Sharptalon  Team Up
Snowfeather Team Up

Bloodgazer Team Rumble
Direbeak Team Rumble
Sharptalon  Team Rumble
Snowfeather Team Rumble

Note: These only count pet-battle world quests in the 7 Broken Isles zones. (Argus and BfA WQs do not count, but Broken Shore and L-Dalaran ones do)

([Guide for these mounts in case it's helpful](https://www.wowhead.com/falcosaur-guide))

**Comment by Urtgard** [comment]
I don't think there is a need to explicitly add this.
You could set the the tracking for "Battle on the Broken Isles" to always on or add the quest ids to the custom tracking.

And you can repeat the pet battles with your alts for a faster progress.
