### ISSUE TITLE
Multiple Errors on build v9.1.0-1

### ISSUE THREAD

**Issue by Yarvillian** [Urtgard/WQAchievements#105]
Just walking around anywhere in game is causing these to spawn. Wish I could be more descriptive but unsure what is causing it and cant seem to figure out whats wrong here :<

105x WQAchievements\WQAchievements-v9.1.0-1.lua:2098: attempt to call field 'CanTransmogItem' (a nil value)
[string "@WQAchievements\WQAchievements-v9.1.0-1.lua"]:2098: in function `IsTransmogable'
[string "@WQAchievements\WQAchievements-v9.1.0-1.lua"]:2400: in function `CheckItems'
[string "@WQAchievements\WQAchievements-v9.1.0-1.lua"]:3072: in function `EmissaryReward'
[string "@WQAchievements\WQAchievements-v9.1.0-1.lua"]:3085: in function `func'
[string "@AngryAssignments\libs\AceTimer-3.0\AceTimer-3.0-17.lua"]:57: in function <...\AngryAssignments\libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:
self = <table> {
watched = <table> {
}
IsQuestFlaggedCompleted = <function> defined @WQAchievements\WQAchievements.lua:3390
UpdateCustomRewards = <function> defined @WQAchievements\Options.lua:1518
SetRewardLinkByID = <function> defined @WQAchievements\WQAchievements.lua:2960
EnableModule = <function> defined @AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:332
modules = <table> {
}
GetRewardForID = <function> defined @WQAchievements\WQAchievements.lua:1678
IterateEmbeds = <function> defined @AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:442
ToggleGet = <function> defined @WQAchievements\Options.lua:1303
CreateCustomQuest = <function> defined @WQAchievements\Options.lua:1389
debug = false
isQuestPinActive = <function> defined @WQAchievements\WQAchievements.lua:3379
slash = <function> defined @WQAchievements\WQAchievements.lua:468
SetDefaultModulePrototype = <function> defined @AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:409
Show = <function> defined @WQAchievements\WQAchievements.lua:1525
itemList = <table> {
}
defaultModuleState = true
AnnouncePopUp = <function> defined @WQAchievements\WQAchievements.lua:2818
IsEnabled = <function> defined @AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:451
ExpansionList = <table> {
}
ScheduleTimer = <function> defined @AngryAssignments\libs\AceTimer-3.0\AceTimer-3.0.lua:94
DisableModule = <function> defined @AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:350
missionList = <table> {
}
CreateCustomMissionReward = <function> defined @WQAchievements\Options.lua:1648
GetArgs = <function> defined @AngryAssignments\libs\AceConsole-3.0\AceConsole-3.0.lua:144
data = <table> {
}
emissaryRewards = false
CreateGroup = <function> defined @WQAchievements\Options.lua:1306
questList = <table> {
}
ZoneIDList = <table> {
}
start = 110.170000
EmissaryReward = <function> defined @WQAchievements\WQAchievements.lua:3059
questPinMapList = <table> {
}
AddRewardToMission = <function> defined @WQAchievements\WQAchievements.lua:1437
CreateCustomReward = <function> defined @WQAchievements\Options.lua:1507
SetEnabledState = <function> defined @AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:424
IsTransmogable = <function> defined @WQAchievements\WQAchievements.lua:2083
enabledState = true
link = <function> defined @WQAchievements\WQAchievements.lua:1664
playerName = "Yarv-Stormrage"
rewards = false
questPinList = <table> {
}
links = <table> {
}
event = <unnamed> {
}
IterateModules = <function> defined @AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:437
optionsFrame = <unnamed> {
}
faction = "Alliance"
db = <table> {
}
baseName = "WQAchievements"
SortOptions = <function> defined @WQAchievements\Options.lua:1710
Reward = <function> defined @WQAchievements\WQAchievements.lua:1939
CancelTimer = <function> defined @AngryAssignments\libs\AceTimer-3.0\AceTimer-3.0.lua:147
CheckWQ = <function> defined @WQAchievements\WQAchievements.lua:1536
AddToys = <function> defined @WQAchievements\WQAchievements.lua:1378
AddMounts = <function> defined @WQAchievements\WQAchievements.lua:1309
OnInitialize = <function> defined @WQAchievements\WQAchievements.lua:277
NewModule = <function> defined @AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:235
Disable = <function> defined @AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:314
CreateQTip = <function> defined @WQAchievements\WQAchievements.lua:2529
AddPets = <function>

**Comment by Leylaa2** [comment]
Hey same for me here.

`88x WQAchievements\WQAchievements-v9.1.0-1.lua:2098: attempt to call field 'CanTransmogItem' (a nil value)
[string "@WQAchievements\WQAchievements-v9.1.0-1.lua"]:2098: in function `IsTransmogable'
[string "@WQAchievements\WQAchievements-v9.1.0-1.lua"]:2400: in function `CheckItems'
[string "@WQAchievements\WQAchievements-v9.1.0-1.lua"]:3072: in function `EmissaryReward'
[string "@WQAchievements\WQAchievements-v9.1.0-1.lua"]:1205: in function `CreateQuestList'
[string "@WQAchievements\WQAchievements-v9.1.0-1.lua"]:1531: in function `?'
[string "@Ace3\AceTimer-3.0\AceTimer-3.0-17.lua"]:55: in function <Ace3\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:
self = <table> {
 watched = <table> {
 }
 IsQuestFlaggedCompleted = <function> defined @WQAchievements\WQAchievements.lua:3390
 UpdateCustomRewards = <function> defined @WQAchievements\Options.lua:1518
 SetRewardLinkByID = <function> defined @WQAchievements\WQAchievements.lua:2960
 EnableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetRewardForID = <function> defined @WQAchievements\WQAchievements.lua:1678
 IterateEmbeds = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 ToggleGet = <function> defined @WQAchievements\Options.lua:1303
 CreateCustomQuest = <function> defined @WQAchievements\Options.lua:1389
 debug = false
 isQuestPinActive = <function> defined @WQAchievements\WQAchievements.lua:3379
 slash = <function> defined @WQAchievements\WQAchievements.lua:468
 SetDefaultModulePrototype = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 Show = <function> defined @WQAchievements\WQAchievements.lua:1525
 itemList = <table> {
 }
 defaultModuleState = true
 AnnouncePopUp = <function> defined @WQAchievements\WQAchievements.lua:2818
 IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 ExpansionList = <table> {
 }
 ScheduleTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:350
 missionList = <table> {
 }
 CreateCustomMissionReward = <function> defined @WQAchievements\Options.lua:1648
 GetArgs = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:144
 data = <table> {
 }
 emissaryRewards = false
 CreateGroup = <function> defined @WQAchievements\Options.lua:1306
 questList = <table> {
 }
 ZoneIDList = <table> {
 }
 start = 333.644000
 EmissaryReward = <function> defined @WQAchievements\WQAchievements.lua:3059
 questPinMapList = <table> {
 }
 AddRewardToMission = <function> defined @WQAchievements\WQAchievements.lua:1437
 CreateCustomReward = <function> defined @WQAchievements\Options.lua:1507
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 IsTransmogable = <function> defined @WQAchievements\WQAchievements.lua:2083
 enabledState = true
 link = <function> defined @WQAchievements\WQAchievements.lua:1664
 playerName = "Leylaâ-Eredar"
 rewards = false
 questPinList = <table> {
 }
 links = <table> {
 }
 event = <unnamed> {
 }
 IterateModules = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:437
 optionsFrame = <unnamed> {
 }
 faction = "Horde"
 db = <table> {
 }
 baseName = "WQAchievements"
 SortOptions = <function> defined @WQAchievements\Options.lua:1710
 Reward = <function> defined @WQAchievements\WQAchievements.lua:1939
 CancelTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:147
 CheckWQ = <function> defined @WQAchievements\WQAchievements.lua:1536
 AddToys = <function> defined @WQAchievements\WQAchievements.lua:1378
 AddMounts = <function> defined @WQAchievements\WQAchievements.lua:1309
 OnInitialize = <function> defined @WQAchievements\WQAchievements.lua:277
 NewModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:235
 Disable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:314
 CreateQTip = <function> defined @WQAchievements\WQAchievements.lua:2529
 AddPets = <function> defined @WQAchievements\WQAchievements.lua:1337
 GetModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:210
 CheckMissions = <function> defined @AddOns`

**Comment by Urtgard** [comment]
That's the update for patch 9.1.
I didn't know that curse & co would distribute this already for the live version.
I reverted the update.
