### ISSUE TITLE
WQ for pet Carpal is shown even if disabled

### ISSUE THREAD

**Issue by cremor** [Urtgard/WQAchievements#106]
The addon shows notifications about WQs that award the item [Animated Ulna](https://www.wowhead.com/item=183111/animated-ulna) for the pet [Carpal](https://www.wowhead.com/npc=173847/carpal) even if the pet is already known.
I thought that it might show it because you can have 3 copies of each pet, so I set the Carpal pet option to "don't track". But I still get the notification about the WQ.

**Comment by Urtgard** [comment]
I'll look into it. Thanks for the notification.

cremor ***@***.***> schrieb am Do., 8. Juli 2021, 18:13:
