### ISSUE TITLE
Update to 9.1.5 causing error, attempt to index field 'tooltip' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [Urtgard/WQAchievements#107]
I'm receiving the following error after logging into the game after the update to 9.1.5. Thanks.

1x WQAchievements\WQAchievements-v9.1.0-2.lua:2856: attempt to index field 'tooltip' (a nil value)
[string "@WQAchievements\WQAchievements-v9.1.0-2.lua"]:2856: in function <WQAchievements\WQAchievements.lua:2854>
[string "=[C]"]: in function `Hide'
[string "@FrameXML\UIParent.lua"]:3535: in function <FrameXML\UIParent.lua:3525>
[string "=[C]"]: ?
[string "=[C]"]: in function `HideUIPanel'
[string "@SharedXML\SharedUIPanelTemplates.lua"]:128: in function <SharedXML\SharedUIPanelTemplates.lua:122>

Locals:
(*temporary) = nil
(*temporary) = <table> {
 activeTooltips = <table> {
 }
 LabelPrototype = <table> {
 }
 tooltipHeap = <table> {
 }
 cellPrototype = <table> {
 }
 tableHeap = <table> {
 }
 providerMetatable = <table> {
 }
 timerHeap = <table> {
 }
 providerPrototype = <table> {
 }
 onReleaseHandlers = <table> {
 }
 LabelProvider = <table> {
 }
 tipMetatable = <table> {
 }
 frameHeap = <table> {
 }
 IterateTooltips = <function> defined @Rarity\Libs\LibQTip-1.0\LibQTip-1.0.lua:167
 CreateCellProvider = <function> defined @Rarity\Libs\LibQTip-1.0\LibQTip-1.0.lua:284
 layoutCleaner = <unnamed> {
 }
 tipPrototype = <table> {
 }
 IsAcquired = <function> defined @Rarity\Libs\LibQTip-1.0\LibQTip-1.0.lua:159
 Release = <function> defined @Rarity\Libs\LibQTip-1.0\LibQTip-1.0.lua:148
 Acquire = <function> defined @Rarity\Libs\LibQTip-1.0\LibQTip-1.0.lua:123
 cellMetatable = <table> {
 }
 frameMetatable = <table> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to index field 'tooltip' (a nil value)"
LibQTip = <table> {
 activeTooltips = <table> {
 }
 LabelPrototype = <table> {
 }
 tooltipHeap = <table> {
 }
 cellPrototype = <table> {
 }
 tableHeap = <table> {
 }
 providerMetatable = <table> {
 }
 timerHeap = <table> {
 }
 providerPrototype = <table> {
 }
 onReleaseHandlers = <table> {
 }
 LabelProvider = <table> {
 }
 tipMetatable = <table> {
 }
 frameHeap = <table> {
 }
 IterateTooltips = <function> defined @Rarity\Libs\LibQTip-1.0\LibQTip-1.0.lua:167
 CreateCellProvider = <function> defined @Rarity\Libs\LibQTip-1.0\LibQTip-1.0.lua:284
 layoutCleaner = <unnamed> {
 }
 tipPrototype = <table> {
 }
 IsAcquired = <function> defined @Rarity\Libs\LibQTip-1.0\LibQTip-1.0.lua:159
 Release = <function> defined @Rarity\Libs\LibQTip-1.0\LibQTip-1.0.lua:148
 Acquire = <function> defined @Rarity\Libs\LibQTip-1.0\LibQTip-1.0.lua:123
 cellMetatable = <table> {
 }
 frameMetatable = <table> {
 }
}
WQA = <table> {
 watched = <table> {
 }
 IsQuestFlaggedCompleted = <function> defined @WQAchievements\WQAchievements.lua:3395
 UpdateCustomRewards = <function> defined @WQAchievements\Options.lua:1518
 SetRewardLinkByID = <function> defined @WQAchievements\WQAchievements.lua:2960
 EnableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetRewardForID = <function> defined @WQAchievements\WQAchievements.lua:1678
 IterateEmbeds = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 ToggleGet = <function> defined @WQAchievements\Options.lua:1303
 CreateCustomQuest = <function> defined @WQAchievements\Options.lua:1389
 debug = false
 isQuestPinActive = <function> defined @WQAchievements\WQAchievements.lua:3384
 slash = <function> defined @WQAchievements\WQAchievements.lua:468
 SetDefaultModulePrototype = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 Show = <function> defined @WQAchievements\WQAchievements.lua:1525
 itemList = <table> {
 }
 defaultModuleState = true
 AnnouncePopUp = <function> defined @WQAchievements\WQAchievements.lua:2818
 IsEnabled = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 ExpansionList = <table> {
 }
 ScheduleTimer = <function> defined @DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 PopUp = WQAchievementsPopUp {
 }
 newTasks = <table> {
 }
 missionList = <table> {
 }
 CreateCustomMissionReward = <function> defined @WQAchievements\Options.lua:1648
 activeTasks = <table> {
 }
 GetArgs = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 dat

**Comment by Urtgard** [comment]
Thanks for the report. I'll look into it.

**Comment by lfstyles** [comment]
I was receiving the same error. Appears that the mount collector addon was interfering with WQA. Disabled MountCollector and its working as intended. Might be a conflicting addon causing his error.
