### ISSUE TITLE
WQ "The World Beyond" is always being tracked

### ISSUE THREAD

**Issue by comiluv** [Urtgard/WQAchievements#108]
1. Description
Shadowlands World Quest [The World Beyond](https://www.wowhead.com/achievement=14758/the-world-beyond) is always tracked even when it's set to "Don't track" in options.
Game version: 9.1.5
Addon version:9.1.5-2

2. Steps to reproduce
1) Open Interface menu
2) Navigate to WQAchievements
3) Click tab named "General"
4) Scroll down to Shadowlands Achievements
5) Set the drop down menu next to The World Beyond to "Don't track"
6) Reload ui

3. Expected result
The achievement is no longer displayed in the addon frame or in the chat box

4. Actual result
The achievement is displayed in the addon frame and in the chat box

**Comment by Urtgard** [comment]
Fixed. Thanks for the detailed report.
