### ISSUE TITLE
Apexis Crystal missing as currency reward for Draenor missions/shipyard

### ISSUE THREAD

**Issue by tflo** [Urtgard/WQAchievements#121]
For some reason [Apexis Crystal](https://www.wowhead.com/currency=823/apexis-crystal) is not selectable as currency reward for the Draenor Garrison/Shipyard missions:

<img width="562" alt="WoWScrnShot_011823_142050" src="https://user-images.githubusercontent.com/1410282/213183326-88603d23-a886-48ac-bb2e-f861bfccf776.png">

Unlike Garrison Resources, Apexis Crystal is still a good reason (and probably the only one) to run Garrison and Shipyard missions, even in DF times, because you can use it to [buy tradable pets](https://www.wowhead.com/currency=823/apexis-crystal#items), which means that Apexis Crystal can be converted directly into gold, if you're playing the AH game.

[Some](https://theunderminejournal.com/#eu/azjolnerub/battlepet/1574) of these pets sell for pretty high prices, which makes Apexis missions very desirable indeed, probably the most profitable missions of all the old-content missions!

(Besides that, you can also buy mounts, if you're still missing those.)

– Tom

**Comment by Urtgard** [comment]
You can track Apexis Crystal with the new version.

**Comment by tflo** [comment]
Wow, that was fast! Thank you 🥰
