### ISSUE TITLE
Error when trying to input a custom event.

### ISSUE THREAD

**Issue by Ookami313** [Urtgard/WQAchievements#13]
Tried to add a custom event to the addon to cover a couple of rares that I still need weapon transmog skins for on Argus and recieved the following error. This occurred when I tried to enter Worldsplitter Skuul's World Quest ID (48834) and the item ID for Praetor's Ornamental Greatsword (153312) into the addon. Thanks.

Date: 2018-08-18 19:40:58
ID: 5
Error occured in: Global
Count: 1
Message: ..\AddOns\WQAchievements\WQAchievements.lua line 260:
   table index is nil
Debug:
   (tail call): ?
   (tail call): ?
   WQAchievements\WQAchievements.lua:260: CreateCustomQuest()
   WQAchievements\WQAchievements.lua:113:
      WQAchievements\WQAchievements.lua:113
   [C]: ?
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:50:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:48
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:789:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:610
   [C]: ?
   ...face\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:71:
      ...face\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:69
   ...face\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:285: Fire()
   ...olic\libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:22:
      ...olic\libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19
Locals:
None
AddOns:

**Comment by Urtgard** [comment]
Make sure you confirm your input. Either push the little ok button or press enter/return.
