### ISSUE TITLE
Add Locales

### ISSUE THREAD

**Issue by Machou** [Urtgard/WQAchievements#133]
Hi

Can you add Locales to translate the addon ?

Regards

**Comment by Urtgard** [comment]
Some phrases were developed with localization in mind.
Feel free to add a PR or comment if you want to provide translations for another locale.

I dont have time to setup something like: https://www.wowace.com/projects/rarity/localization

https://github.com/Urtgard/WQAchievements/blob/11320e5fae28438705a75b3ab3970ae61882d728/WQAchievements.lua#L15-L52
