### ISSUE TITLE
[Feature Request] Add World Quest Reward Currency Type

### ISSUE THREAD

**Issue by nylathak** [Urtgard/WQAchievements#139]
Hello there, awesome addon.
On the tab where you add Rewards there's no option to add currency like Bloody Tokens. 
https://www.wowhead.com/currency=2123/bloody-tokens
When you try to add the number 2123 you get instead
https://www.wowhead.com/item=2123/cracked-leather-boots
Would be nice to be able to track those bloody tokens since they are hard to farm and the quests for them appear once a week.

**Comment by Urtgard** [comment]
Since there aren't that much possible currency rewards I don't think it's necessary to add custom currency tracking.

Added Bloody Tokens as a trackable currency. Check `Rewards - Dragon Flight - World Quests - Currencies` to enable tracking.
