### ISSUE TITLE
attempt to index field 'tooltip' (a nil value)

### ISSUE THREAD

**Issue by Quartzfire** [Urtgard/WQAchievements#140]
32x WQAchievements/WQAchievements.lua:2240: attempt to index field 'tooltip' (a nil value)
[string "@WQAchievements/WQAchievements.lua"]:2240: in function <WQAchievements/WQAchievements.lua:2238>
[string "=[C]"]: in function `Hide'
[string "@FrameXML/UIParent.lua"]:3265: in function `HideUIPanel'
[string "@SharedXML/SharedUIPanelTemplates.lua"]:154: in function <SharedXML/SharedUIPanelTemplates.lua:145>

Locals:
(*temporary) = nil
(*temporary) = <table> {
 activeTooltips = <table> {
 }
 LabelPrototype = <table> {
 }
 tooltipHeap = <table> {
 }
 cellPrototype = <table> {
 }
 tableHeap = <table> {
 }
 providerMetatable = <table> {
 }
 timerHeap = <table> {
 }
 providerPrototype = <table> {
 }
 onReleaseHandlers = <table> {
 }
 LabelProvider = <table> {
 }
 tipMetatable = <table> {
 }
 frameHeap = <table> {
 }
 IterateTooltips = <function> defined @Rarity/Libs/LibQTip-1.0/LibQTip-1.0.lua:162
 CreateCellProvider = <function> defined @Rarity/Libs/LibQTip-1.0/LibQTip-1.0.lua:280
 layoutCleaner = Frame {
 }
 tipPrototype = <table> {
 }
 IsAcquired = <function> defined @Rarity/Libs/LibQTip-1.0/LibQTip-1.0.lua:154
 Release = <function> defined @Rarity/Libs/LibQTip-1.0/LibQTip-1.0.lua:143
 Acquire = <function> defined @TipTac/ttCore.lua:415
 cellMetatable = <table> {
 }
 frameMetatable = <table> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to index field 'tooltip' (a nil value)"
LibQTip = <table> {
 activeTooltips = <table> {
 }
 LabelPrototype = <table> {
 }
 tooltipHeap = <table> {
 }
 cellPrototype = <table> {
 }
 tableHeap = <table> {
 }
 providerMetatable = <table> {
 }
 timerHeap = <table> {
 }
 providerPrototype = <table> {
 }
 onReleaseHandlers = <table> {
 }
 LabelProvider = <table> {
 }
 tipMetatable = <table> {
 }
 frameHeap = <table> {
 }
 IterateTooltips = <function> defined @Rarity/Libs/LibQTip-1.0/LibQTip-1.0.lua:162
 CreateCellProvider = <function> defined @Rarity/Libs/LibQTip-1.0/LibQTip-1.0.lua:280
 layoutCleaner = Frame {
 }
 tipPrototype = <table> {
 }
 IsAcquired = <function> defined @Rarity/Libs/LibQTip-1.0/LibQTip-1.0.lua:154
 Release = <function> defined @Rarity/Libs/LibQTip-1.0/LibQTip-1.0.lua:143
 Acquire = <function> defined @TipTac/ttCore.lua:415
 cellMetatable = <table> {
 }
 frameMetatable = <table> {
 }
}
WQA = <table> {
 watched = <table> {
 }
 IsQuestFlaggedCompleted = <function> defined @WQAchievements/WQAchievements.lua:2785
 UpdateCustomRewards = <function> defined @WQAchievements/Options.lua:1470
 SetRewardLinkByID = <function> defined @WQAchievements/WQAchievements.lua:2347
 EnableModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetRewardForID = <function> defined @WQAchievements/WQAchievements.lua:973
 IterateEmbeds = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:438
 ToggleGet = <function> defined @WQAchievements/Options.lua:1255
 CreateCustomQuest = <function> defined @WQAchievements/Options.lua:1341
 PopUp = WQAchievementsPopUp {
 }
 debug = false
 isQuestPinActive = <function> defined @WQAchievements/WQAchievements.lua:2774
 slash = <function> defined @WQAchievements/WQAchievements.lua:507
 SetDefaultModulePrototype = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 newTasks = <table> {
 }
 Show = <function> defined @WQAchievements/WQAchievements.lua:798
 itemList = <table> {
 }
 defaultModuleState = true
 AnnouncePopUp = <function> defined @WQAchievements/WQAchievements.lua:2202
 IsEnabled = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 ExpansionList = <table> {
 }
 ScheduleTimer = <function> defined @Ace3/AceTimer-3.0/AceTimer-3.0.lua:94
 DisableModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:346
 activeTasks = <table> {
 }
 emissaryRewards = true
 missionList = <table> {
 }
 CreateCustomMissionReward = <function> defined @WQAchievements/Options.lua:1600
 UpdateOptions = <function> defined @WQAchievements/Options.lua:161
 GetArgs = <function> defined @Ace3/AceConsole-3.0/AceConsole-3.0.lua:140
 data = <table> {

**Comment by Urtgard** [comment]
Can you reproduce the error or does it happen more or less randomly every now and then?

Does this also happen if you deactivate your other addons?

**Comment by Quartzfire** [comment]
Seems to happen under the following circumstances:

I log into game.

I have WQA set to load after 20 seconds (don't think that makes any difference), so my screen something like this:

![image](https://github.com/Urtgard/WQAchievements/assets/76067897/f5c1a158-1700-47c6-9814-8e802f4dfc43)

If I don't close WQA and leave it until I go AFK or manually go afk with /AFK, I have an addon called "AFK Fullscreen Warning" that kicks in and shows a nice AFK screen e.g.

![image](https://github.com/Urtgard/WQAchievements/assets/76067897/982399a7-e111-45b3-881d-f1c93cae8697)

When I come back to my PC and come out of being AFK, the WQA screen is still there, but is now blank e.g.

![image](https://github.com/Urtgard/WQAchievements/assets/76067897/09f79952-9d6d-440c-ac52-f2e4ba0ea8e2)

When I close the WQA window, that is when the LUA happens e.g.

![image](https://github.com/Urtgard/WQAchievements/assets/76067897/4424517d-b3a9-43f4-9ef4-04d75de5fe5b)

Doesn' seem that I can reproduce it when I disable "AFK Fullscreen Warning" addon.

I hope this helps?

**Comment by Quartzfire** [comment]
Hi,

 

I added details of how I can reproduce it to the github ticket.

 

Hope it helps you.

 

Cheers,

Quartz

**Comment by Urtgard** [comment]
That definitely helps. Very good description.

Preventing the error should be pretty easy. I just have to check whether the tooltip is active when we close the main window.

With the empty window, I don't know how complicated it is. Maybe I'll leave that for later.
