### ISSUE TITLE
Add on not working

### ISSUE THREAD

**Issue by Will-H71** [Urtgard/WQAchievements#146]
Hi, I have downloaded the add on but it isnt showing up in my add on list.

**Comment by Urtgard** [comment]
How did you install WQA?
The addon files must be placed in this folder `World of Warcraft\_retail_\Interface\AddOns\WQAchievements`

**Comment by Will-H71** [comment]
I discussed this with a friend and having extracted and installed it via the Curseforge app, rather than by downloading and then extracting to the folder it worked. I cannot explain why the latter method didn't work this time, seeing as I've used that to extract and install AllTheThings, RareScanner and HandyNotes just fine. If you have any ideas I'd be happy to hear them, but as it stands I now have the WQA add-on properly installed.

**Comment by Urtgard** [comment]
Maybe you accidentally created one folder too many. Like `AddOns\WQAchievements\WQAchievements`
