### ISSUE TITLE
Plans to support TWW zones/currencies/achievements?

### ISSUE THREAD

**Issue by SoulCookie** [Urtgard/WQAchievements#159]
Hi! Just wondering if you're planning on extending the addon to work with the new stuff in The War Within.

If so, and if you're comfortable sharing it, do you have a projected timeframe for implementation?

Thanks in advance!

**Comment by Zeeda17** [comment]
I added the new zones and made a PR https://github.com/Urtgard/WQAchievements/pull/160 This shows ilvl upgrades and uncollected mog. Achievements will still need to be added.

**Comment by Urtgard** [comment]
Yes, I plan to update it for TWW as well.
But I'm not that active at the moment.
Unless someone jumps in and helps with a PR, it might take a while.

**Comment by Hyphie24** [comment]
I added some achievement stuff, I can submit that

**Comment by Urtgard** [comment]
@Hyphie24 added a lot of TWW stuff. Thank you for that.

If something is wrong or missing please open a new issue.
