### ISSUE TITLE
Weird stray frame appearing randomly, probably caused by WQA

### ISSUE THREAD

**Issue by tflo** [Urtgard/WQAchievements#164]
Sometimes I get a stray frame like this:

<img width="458" alt="WoWScrnShot_091024_131325 copy" src="https://github.com/user-attachments/assets/fd027d2d-14c7-4c13-b9c8-0c90558f0608">

The name of the frame is `WQTItemTooltipScan` and it is anchored to the mouse. It seems to appear randomly, but when it does, it only appears right after login; a reload is required to get rid of it.

Grepping through my AddOns folder brought me to the only possible non-Blizz origin of this frame, in WQAchievements/WQAchievements.lua, line 882:

```lua
ItemTooltipScan = CreateFrame("GameTooltip", "WQTItemTooltipScan", UIParent, "InternalEmbeddedItemTooltipTemplate")
ItemTooltipScan.texts = {
	_G["WQTItemTooltipScanTooltipTextLeft1"],
	_G["WQTItemTooltipScanTooltipTextLeft2"],
	_G["WQTItemTooltipScanTooltipTextLeft3"],
	_G["WQTItemTooltipScanTooltipTextLeft4"]
}
ItemTooltipScan.patern = ITEM_LEVEL:gsub("%%d", "(%%d+)") --from LibItemUpgradeInfo-1.0
```

I couldn’t find any references to `ItemTooltipScan` in the rest of the addon, and also not in any other addon I have in my current AddOns folder or in my Archived AddOns folder. So, I’m wondering what the purpose of this is?

If the frame is needed for some interaction with an unknown addon, then I suggest creating it only when that other addon is loaded.

I’m currently running WQA with the entire block (lines 882–889) commented out, and everything seems to be working fine, so far.

**Comment by Urtgard** [comment]
At first glance it looks like you're right and it's useless now.
I suspect this is a relic of an ancient time when it was necessary to scan tooltips to get certain information.

**Comment by tflo** [comment]
> useless now

Above all, it produces a stray frame (see screenshot in OP).

Since I've posted, I'm running WQA with the offending `ItemTooltipScan` lines commented out, and no problems so far. And the stray frame didn't appear, of course.

But as said, I'm not using WQT, so I cannot tell if removing the lines cuts off some interactive functionality with WQT. But looking at what WQT does in regards to the `WQTItemTooltipScan` frame and `ItemTooltipScan` table (which is local in WQT) and what WQA does, the code doesn't make any sense – to me.

**Comment by tflo** [comment]
Thanks for the update (11.0.5-1) today!

Any plans to resolve this issue too?

Here the diff, rebased on 11.0.5-1:

```diff
diff --git a/WQAchievements/WQAchievements.lua b/WQAchievements/WQAchievements.lua
--- a/WQAchievements/WQAchievements.lua
+++ b/WQAchievements/WQAchievements.lua
@@ -801,20 +801,11 @@
 local EquipLocToSlot2 = {
 	INVTYPE_FINGER = 12,
 	INVTYPE_TRINKET = 14,
 	INVTYPE_WEAPON = 17
 }
 
-ItemTooltipScan = CreateFrame("GameTooltip", "WQTItemTooltipScan", UIParent, "InternalEmbeddedItemTooltipTemplate")
-ItemTooltipScan.texts = {
-	_G["WQTItemTooltipScanTooltipTextLeft1"],
-	_G["WQTItemTooltipScanTooltipTextLeft2"],
-	_G["WQTItemTooltipScanTooltipTextLeft3"],
-	_G["WQTItemTooltipScanTooltipTextLeft4"]
-}
-ItemTooltipScan.patern = ITEM_LEVEL:gsub("%%d", "(%%d+)") --from LibItemUpgradeInfo-1.0
-
 local ReputationItemList = {
 	-- Army of the Light Insignia
 	[152957] = 2165,
 	[152955] = 2165,
 	[152956] = 2165,
```

**Comment by Urtgard** [comment]
Thanks for the reminder. I had totally forgotten about that.
