### ISSUE TITLE
Game stutters/lags every 2-3 second for 1 second with WQA addon active

### ISSUE THREAD

**Issue by keflatbn** [Urtgard/WQAchievements#167]
Hi,
First thanks for a great addon, been using it for a long time <3

Today the game was almost unplayable with WQA enabled. Every 2-3 second the framerate drops from 117 to 75 and the game freezes 1 second. I have a bunch of addons but I decided to disable the top 3 memory users (AllTheThings, Details and WQA) to see if any of those where the problem.
Started with ATT, then Details without any change, last I disabled was WQA and the stutter dissapeared. 
I then enabled the two other again and still no stutter. When I enabled WQA again the stutter was back

I'm using version 11.0.2-4 with latest Retail

**Comment by Hyphie24** [comment]
Is there an error that pops from it?

**Comment by keflatbn** [comment]
Hi, thanks for a fast reply.
No, unfortunatly there is no error that pops up (I have buggrabber/bugsack installed and they report nothing) its just the stutters.
I tested with all addons disabled except for WQA and the stutter was still there.
I tested different TWW zones too to see if it was zone related, but I had the problem regardless of TWW zone.
I currently have all addons except TWW enabled and no stutter.

**Comment by Urtgard** [comment]
Have you tried resetting your profile? All you have to do is delete the WQAchievements.lua in the WTF folder.

`World of Warcraft\_retail_\WTF\Account\YOUR_ACCOUNT_NAME\SavedVariables\WQAchievements.lua`

**Comment by keflatbn** [comment]
Hi again,
I did reset the Savevariables via the Curseforge app, and I currently do not have any stutter.
Is there any drawback to resetting the addons saved variables? If not then thats a acceptable workaround :)

**Comment by Hyphie24** [comment]
The only thing resetting saved variables is it basically puts the addon to a default state. So any personal changes made get removed, so any manual tracking items, quests, etc
But glad to hear that fixed, I did notice there was some addon changes too, that may have helped

**Comment by keflatbn** [comment]
Ty for the quick reply, lets close this then! :)
