### ISSUE TITLE
bug compare

### ISSUE THREAD

**Issue by Addonman** [Urtgard/WQAchievements#170]
Not sure if its related with this addon or not since error i see was reported before
Message: bad argument #1 to '?' (Usage: local info = C_QuestLog.GetQuestTagInfo(questID))
Debug:
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/WQAchievements/WQAchievements.lua"]:936: Reward()
   [string "@Interface/AddOns/WQAchievements/WQAchievements.lua"]:289: CreateQuestList()
   [string "@Interface/AddOns/WQAchievements/WQAchievements.lua"]:454: ?()
   [string "@Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua"]:55:
      Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50
this is error i get from this addon
but i also get achievement frame trying to compare me or with ppl i group up in  game.Does this addon  trigger something like that?

**Comment by Machou** [comment]
@Addonman go here and remplace all file by the PR:
https://github.com/Urtgard/WQAchievements/pull/169

Works for me !

**Comment by Addonman** [comment]
10x ill try that.Compare issues is from other addon btw.
