### ISSUE TITLE
LDB

### ISSUE THREAD

**Issue by Urtgard** [Urtgard/WQAchievements#19]

**Comment by NLZ** [comment]
I was just thinking about suggesting it, would be less intrusive to have a broker.

**Comment by Urtgard** [comment]
v8.0.1-27 brings LDB support. Tested it only with TitanPanel.

**Comment by NLZ** [comment]
Ah, sorry for not getting back to you in time. Its working fine with ChocolateBar (another LDB display addon), thank you.

**Comment by Urtgard** [comment]
Good to know.
