### ISSUE TITLE
"Bless the Rains Down in Freehold" not shown

### ISSUE THREAD

**Issue by cremor** [Urtgard/WQAchievements#22]
The world quest [Swab This!](https://www.wowhead.com/quest=52159/swab-this) is up right now, but the addon doesn't show that is interesting for the achievement [Bless the Rains Down in Freehold](https://www.wowhead.com/achievement=13050/bless-the-rains-down-in-freehold)

I made sure that it is checked in the options.

edit: Seems like there are two quests, one for Horde and one for Alliance. You are only checking the Horde one. The one I linked above is for the Alliance. This lets me wonder how many other Alliance quests are missing...

**Comment by Urtgard** [comment]
Thanks for the report.
Most data is from wowhead before BfA was released. So maybe something else is missing.

I only have the ID for the WQ with the green sabertron for _Sabertron Assemble_
