### ISSUE TITLE
Sabertron Assemble world quests

### ISSUE THREAD

**Issue by cremor** [Urtgard/WQAchievements#23]
https://www.wowhead.com/quest=51976/sabertron (seems like you already have that one)
https://www.wowhead.com/quest=51977/sabertron
https://www.wowhead.com/quest=51978/sabertron

One is still missing, seems like it's not on Wowhead yet. Maybe it's 51973 or 51974 (those two are near the other Ids and unknown to Wowhead right now).

**Comment by Urtgard** [comment]
Yes, that's for green. It was active a few weeks ago.

From wowhead:
> By default it spawns in red color, to get a different color you have to do a world quests on Sabertron.
There are 4 world quests on it with the same name, the difference is that each quest spawns different color.

Looks like we need only one more. I'll add the other two quests.

**Comment by cremor** [comment]
https://www.wowhead.com/quest=51977/sabertron (yellow Sabertron) is up on EU right now, but the addon didn't notify me although I was still missing it.

**Comment by Urtgard** [comment]
Thanks for the report.

My bad. I didn't add the quests.

I added both IDs in the new version.

**Comment by Urtgard** [comment]
Thanks again. A new version is on it's way.

Was the orange version active already? The ID is probably 51978.

**Comment by cremor** [comment]
I don't have the orange one personally, but yes, it has to be 51978.
