### ISSUE TITLE
bad argument #3 to 'format' (string expected, got nil)

### ISSUE THREAD

**Issue by Ookami313** [Urtgard/WQAchievements#29]
After updating to 16beta I'm getting the following error upon logging in. Thanks.

Date: 2018-09-23 17:07:27
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\WQAchievements\WQAchievements.lua line 522:
   bad argument #3 to 'format' (string expected, got nil)
Debug:
   (tail call): ?
   [C]: ?
   [C]: format()
   WQAchievements\WQAchievements.lua:522: AnnounceChat()
   WQAchievements\WQAchievements.lua:433: ?()
   ...\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:55:
      ...\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:50
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:

**Comment by Urtgard** [comment]
fixed in v8.0.1-17beta
