### ISSUE TITLE
Fishing 'Round the Isles not working?

### ISSUE THREAD

**Issue by Tecfan** [Urtgard/WQAchievements#35]
Checked all my settings, everything seems in order. I just noticed that Raft Fishing is up in Azsuna, but the addon does not warn me about this. Come to think of it, I have never ever seen a warning for the fishing wq's, and I have only completed about half of them. Possibly bugged? Latest version.

**Comment by Urtgard** [comment]
Thanks for the report.

The new version should track this achievement correctly again. (https://github.com/Urtgard/WQAchievements/releases/tag/v8.0.1-29release if you don't want to wait for curse)

**Comment by Tecfan** [comment]
This one is not working either: https://www.wowhead.com/quest=41253/migrating-highmountain-salmon

**Comment by Urtgard** [comment]
I can't test this right now myself.

First the obvious things: you don't have this achievement and you don't have this criteria?

Please run these (when the quest is active) in the chat and post the results so I can easier find the bug.

/dump WQAchievements.questList[41253]
/dump C_TaskQuest.IsActive(41253)

**Comment by Tecfan** [comment]
Yes, I'm sure, as I went ahead and did the WQ and the achievement popped for me. Can't test any longer I'm afraid.

**Comment by Urtgard** [comment]
Which version do you use?

I'll take a look.

**Comment by Urtgard** [comment]
Found the error.

I got one } too much in my data.

Because of that little bracket the tracking for the last 5 quests (Migrating Highmountain Salmon, Rocket Boot Fishing, Work Order Mossgill Perch, Work Order: Runescale Koi, The Angler Mangler) was useless.

Again thank you for the report!
