### ISSUE TITLE
attempt to perform arithmetic on local 't' (a nil value)

### ISSUE THREAD

**Issue by Fett1138** [Urtgard/WQAchievements#38]
Message: Interface\AddOns\WQAchievements\WQAchievements.lua:1510: attempt to perform arithmetic on local 't' (a nil value)
Time: Wed Dec 26 02:34:30 2018
Count: 1
Stack: Interface\AddOns\WQAchievements\WQAchievements.lua:1510: attempt to perform arithmetic on local 't' (a nil value)
Interface\AddOns\WQAchievements\WQAchievements.lua:1510: in function `formatTime'
Interface\AddOns\WQAchievements\WQAchievements.lua:710: in function `AnnounceChat'
Interface\AddOns\WQAchievements\WQAchievements.lua:603: in function `?'
...ns\WQAchievements\Libs\AceTimer-3.0\AceTimer-3.0.lua:55: in function <...ns\WQAchievements\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals: self = <table> {
 watched = <table> {
 }
 UpdateCustomRewards = <function> defined @Interface\AddOns\WQAchievements\Options.lua:946
 SetRewardLinkByID = <function> defined @Interface\AddOns\WQAchievements\WQAchievements.lua:1333
 EnableModule = <function> defined @Interface\AddOns\WQAchievements\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetRewardForID = <function> defined @Interface\AddOns\WQAchievements\WQAchievements.lua:629
 IterateEmbeds = <function> defined @Interface\AddOns\WQAchievements\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 ToggleGet = <function> defined @Interface\AddOns\WQAchievements\Options.lua:821
 CreateCustomQuest = <function> defined @Interface\AddOns\WQAchievements\Options.lua:866
 debug = false
 slash = <function> defined @Interface\AddOns\WQAchievements\WQAchievements.lua:188
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\WQAchievements\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 Show = <function> defined @Interface\AddOns\WQAchievements\WQAchievements.lua:526
 emissaryRewards = true
 defaultModuleState = true
 AnnouncePopUp = <function> defined @Interface\AddOns\WQAchievements\WQAchievements.lua:1235
 IsEnabled = <function> defined @Interface\AddOns\WQAchievements\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 ExpansionList = <table> {
 }
 ScheduleTimer = <function> defined @Interface\AddOns\WQAchievements\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Interface\AddOns\WQAchievements\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 SortQuestList = <function> defined @Interface\AddOns\WQAchievements\WQAchievements.lua:1386
 GetArgs = <function> defined @Interface\AddOns\WQAchievements\Libs\AceConsole-3.0\AceConsole-3.0.lua:144
 data = <table> {
 }
 questList = <table> {
 }
 ZoneIDList = <table> {
 }
 EmissaryReward = <function> defined @Interface\AddOns\WQAchievements\WQAchievements.lua:1400
 activeQuests = <table> {
 }
 CreateCustomReward = <function> defined @Interface\AddOns\WQAchievements\Options.lua:940
 SetEnabledState = <function> defined @Interface\AddOns\WQAchievements\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 link = <function> defined @Interface\AddOns\WQAchievements\WQAchievements.lua:612
 rewards = true
 links = <table> {
 }
 IterateModules = <function> defined @Interface\AddOns\WQAchievements\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
 newQuests = <table> {
 }
 Reward = <function> defined @Interface\AddOns\WQAchievements\WQAchievements.lua:781
 CheckWQ = <function> defined @Interface\AddOns\WQAchievements\WQAchievements.lua:537
 GetRewardTextByID = <function> defined @Interface\AddOns\WQAchievements\WQAchievements.lua:1277
 AddMounts = <function> defined @Interface\AddOns\WQAchievements\WQAchievements.lua:412
 OnInitialize = <function> defined @Interface\AddOns\WQAchievements\WQAchievements.lua:90
 NewModule = <function> defined @Interface\AddOns\WQAchievements\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 CreateQTip = <function> defined @Interface\AddOns\WQAchievements\WQAchievements.lua:1097
 AddPets = <function> defined @Interface\AddOns\WQAchievements\WQAchievements.lua:431
 GetModule = <function> defined @Interface\AddOns\WQAchievements\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 AddAchievements = <function> defined @Interface\AddOns\WQAchievements\WQAchievements.lua:375
 AddEmissaryRe

**Comment by Urtgard** [comment]
I'll fix it when I'm back home.

**Comment by Urtgard** [comment]
Fixed in the new version. If the remaining time isn't available it's now 0m.

**Comment by Fett1138** [comment]
Many thanks!
