### ISSUE TITLE
When wearing Azerite armor, the upgrade calculation for regular (Legion) gear rewards fails

### ISSUE THREAD

**Issue by SacredDuckwhale** [Urtgard/WQAchievements#45]
This is likely due to the Azerite pieces having no secondary stats. Here's how it looks:

![Screenshot](https://i.imgur.com/ukOTIs5.png)

**Comment by Urtgard** [comment]
Do you use Pawn or StatWeightScore?
Does this happen always or just sometimes?
If you mouseover the item, is the tooltip correct or do you see the wrong number there too?

**Comment by SacredDuckwhale** [comment]
* Yes, I'm using Pawn
* Disabling it removes the percentage altogether
* It happens whenever a Legion WQ has an item that I don't own the appearance of
* The tooltip simply displays "upgrade", with the green arrow icon, but doesn't give any percentage (number)

I think Pawn is also confused by the lack of stats. But WQA could try to find out when the percentage is absurdly high, or filter gear upgrades from Legion WQ as a workaround?

**Comment by Urtgard** [comment]
If an upgrade is greater than 1000% it won't be tracked.
You shouldn't see absurdly high and wrong upgrades anymore.
