### ISSUE TITLE
Add Master Calligrapher achievement

### ISSUE THREAD

**Issue by cremor** [Urtgard/WQAchievements#46]
Patch 8.1.5 brought a new achievement: [Master Calligrapher](https://www.wowhead.com/achievement=13512/master-calligrapher)

I'm not 100% sure about this, but it seems like each world quest offers only one part of the achievement (similar to Sabertron Assemble).

I've just completed [Quest 55264](https://www.wowhead.com/quest=55264/calligraphy) and it was the square pattern. WowHead lists all other Calligraphy quests under "See also", but we'll have to figure out which quest is for which pattern.

edit:
https://www.wowhead.com/quest=55340/calligraphy is the circle pattern.

**Comment by Urtgard** [comment]
As always, thanks for the info.

Master Calligrapher is now part of  v8.1.0-11beta

Let me know, if you have more infos about the other quests.

**Comment by cremor** [comment]
https://www.wowhead.com/quest=55341/calligraphy is the triangle.

**Comment by cremor** [comment]
It seems like both Alliance and Horde have exactly 3 Calligraphy quests. Since I'm only playing Alliance I won't be able to provide any more information about which remaining quest Ids are for which pattern.
