### ISSUE TITLE
Equipment tooltips not showing information.

### ISSUE THREAD

**Issue by Ookami313** [Urtgard/WQAchievements#50]
Curious to know if anyone else has been seeing the following issue.
![WQA1](https://user-images.githubusercontent.com/26803942/57188183-5cbe4a00-6ec8-11e9-8106-fad8675bae60.jpg)
I noticed the above issue about the time 8.1.5 was released, but held off reporting in hopes that the issue would be resolved . It was a minor (in my opinion) issue, but another addon I have been using (BonusRollPreview) was having the same issue, and the author just responded to their ticket stating that they had figured out what the issue was and corrected it. It seems, according to them, that the issue lies within compare tooltips and a user having "always compare" turned on. Not sure if this is helpful or not. Tooltips for other items in the information box do not seem to be affected.

Also, another minor issue I was hoping you could take a look at. Is there anyway to adjust the strata of the upper bar so that it is at the same level as the body of the rest of the information box? Currently if I have something like my map open and the addon updates with new WQs, I have to close my map before I can reach the X to close WQA. See below.
![WQA2](https://user-images.githubusercontent.com/26803942/57188376-99d80b80-6ecb-11e9-8a39-afad4513b5d8.jpg)
![WQA3](https://user-images.githubusercontent.com/26803942/57188378-9e042900-6ecb-11e9-9e04-7fd420b006c1.jpg)

Thanks.

**Comment by Urtgard** [comment]
If you notice a problem let me know as soon as possible.

I rarely use the popup, so I didn't even knew about this bugs.

I'll look into it in the next week.

**Comment by Urtgard** [comment]
Yes, it was the same problem with "always compare".

The popup is now all on the same frame level.
