### ISSUE TITLE
Pets from "Battle Bots" WQ

### ISSUE THREAD

**Issue by cremor** [Urtgard/WQAchievements#52]
Could you please add the WQ Battle Bots ([Alliance](https://www.wowhead.com/quest=54272/battle-bots)/[Horde](https://www.wowhead.com/quest=54273/battle-bots))? If you do it a few times and loot the chest that spawns if "your" pet wins, you can get the pet [Rebuilt Gorilla Bot](https://www.wowhead.com/item=166715/rebuilt-gorilla-bot) (Alliance)/[Rebuilt Mechanical Spider](https://www.wowhead.com/item=166723/rebuilt-mechanical-spider) (Horde).

**Comment by Urtgard** [comment]
https://github.com/Urtgard/WQAchievements/releases/tag/v8.2.0-1release
