### ISSUE TITLE
So ANGRY

### ISSUE THREAD

**Issue by strawberryga** [Urtgard/WQAchievements#55]
NOT getting alerts when World Quest is up for the Adventurer Achievement. I get the alerts on some characters but the one character that only has a few left has gotten nothing for a month, imagine my surprise today when a random kill popped the Adventurer Achievement but the wqa did not alert me... it's been a month since I have gotten any adventurer alerts, I dont know why except its been since the update.

**Comment by Urtgard** [comment]
At the time the Adventurere Achievements were added there were some rares without a world quest. (Don't know if this changed in the meantime)

Which rare was missing for the achievement?
Was the rare part of a world quest?
