### ISSUE TITLE
"By de Power of de Loa!" achievement missing

### ISSUE THREAD

**Issue by eFse7en** [Urtgard/WQAchievements#59]
Missing "By de Power of de Loa!" achievement [id: 13035]
dependent on "Hundred Troll Holdout" world quest [id: 51178] in Zuldazar
https://www.wowhead.com/achievement=13035/by-de-power-of-de-loa#comments:id=2574857

**Comment by Urtgard** [comment]
Why do you think it's missing?
Didn't you get a notification while it was active? Have you checked the settings? Maybe you did it with another character previously?

I don't have time to check it ingame but the data you posted is already part of the addon.

**Comment by eFse7en** [comment]
I definitely haven't completed it on other characters, and I had running WQAchievements for a very long time, and I realized I am missing this achievement only after installing another addon.

**Comment by Urtgard** [comment]
Do you play horde? Are you 100% sure that 51178 was the questID of the wq?

I noticed there are two different quests. Maybe one is for horde and one for alliance.
Or maybe the quest got replaced. WQA is looking for both IDs now.

https://www.wowhead.com/quest=51232
https://www.wowhead.com/quest=51178

**Comment by eFse7en** [comment]
I didn't verify the WQ id when it was up. I just assumed that linked wowhead page had corrent information.
anyway I've checked data used by AllTheThings addon, and it seems that the quest ids you've recently provided are correct:
`q(51178, g({
		lvl = 120,
		isWorldQuest = 1,
		r = 2
	}, {
		ach(13035)
	})),
q(51232, g({
		lvl = 120,
		isWorldQuest = 1,
		r = 1
	}, {
		ach(13035)
	})),
`
