### ISSUE TITLE
Popup box size limited

### ISSUE THREAD

**Issue by NLZ** [Urtgard/WQAchievements#6]
![capture](https://user-images.githubusercontent.com/884277/43356400-7bec5988-9270-11e8-8e41-1ec8b9973fad.PNG)

There is a size limit for the popup box.

Could you make it auto expanding or give it a scroll bar?

Not overly important, just in case you are bored.

**Comment by NLZ** [comment]
Correction, it just seems like the first line is always out of bounds.

**Comment by NLZ** [comment]
Ah, that makes more sense, thank you for your work. :)

**Comment by Urtgard** [comment]
I finally reworked the PopUp.
Would be nice if you could test it: https://github.com/Urtgard/WQAchievements/releases/tag/v8.0.1-15alpha
