### ISSUE TITLE
[Request] Tracking World Quests rewarding custom currency

### ISSUE THREAD

**Issue by eFse7en** [Urtgard/WQAchievements#62]
I'm interested in tracking world quests which reward Conquest points (at least when I'm not capped), but I couldn't find a way to do it other than searching for all world quests which rewards conquest points and manually adding them in.

**Comment by Urtgard** [comment]
In the new version you can activate tracking for conquest points: https://github.com/Urtgard/WQAchievements/releases/tag/v8.2.5-4beta

I didn't test anything. I just added the currencyID.

Let me know how the tracking works.

**Comment by eFse7en** [comment]
Thank you. I will test it, when next conquest WQ shows up.

**Comment by eFse7en** [comment]
Works like a charm for Conquest points. Thanks!
![image](https://user-images.githubusercontent.com/33643124/68980197-0a0f0480-0800-11ea-8c8e-9d8cca33d9e7.png)
