### ISSUE TITLE
[Request] Conditional formatting for remaining WQ time

### ISSUE THREAD

**Issue by eFse7en** [Urtgard/WQAchievements#63]
I often use `/wqa popup` to check what to do, and it's nice that it's grouped by location, but I would also like to be able to spot faster if items will expire soon (before I will be able to work on them again).
Maybe the same colors could be used like for World Quest List addon, to be intuitional for other users as well:
- <=30min red
- <=180min yellow
- else - white (current)

**Comment by Urtgard** [comment]
Good (and easy to implement) idea.
I'll add it in a new version.

**Comment by Urtgard** [comment]
Added in v8.2.5-5

**Comment by eFse7en** [comment]
Works, thanks.
