### ISSUE TITLE
Missing reminder about [Clues Abound] quest for [Outside Influences] achievement

### ISSUE THREAD

**Issue by eFse7en** [Urtgard/WQAchievements#65]
7 criteria for achievement https://www.wowhead.com/achievement=13556/outside-influences can be done with the same quest: https://www.wowhead.com/quest=55658/clues-abound#comments:id=3137779
I'm missing 5 criteria, but I am not reminded about this daily quest being available in Mechagon Island.
![image](https://user-images.githubusercontent.com/33643124/69382080-91ec8700-0cb6-11ea-898f-0c2fd8507799.png)

Workaround: Custom quest pin added for quest id: 55658 and mapID: 1462

**Comment by Urtgard** [comment]
Good to know. I'll correct this.

Are this the only quests you need? For some quests none of my detection methods works, so you must visit Mechagon to check it (or maybe it's on wowhead).

**Comment by eFse7en** [comment]
I was in Mechagon multiple times and it was still not showing a reminder for those achievement criteria, but those were the only one i was missing. I have either completed the rest on my own or was reminded about it.

**Comment by Urtgard** [comment]
Added 55658 for those criterias. One little problem, you'll get a notification like: [Clues Abound] for [Outside Influences] & [Outside Influences] & [Outside Influences]

But I'm not really motivated to fix this right now.

**Comment by Urtgard** [comment]
#67
