### ISSUE TITLE
[Request] Reminder for Zuldazar: [Wrath of Rezan] WQ for a toy

### ISSUE THREAD

**Issue by eFse7en** [Urtgard/WQAchievements#66]
There's a world quest which has a 100% chance to give a toy after completion. It could be monitored by the addon for other players:
https://www.wowhead.com/quest=50957/wrath-of-rezan#comments
WQ id is correct, and it is up today(2019-11-25) on EU.

**Comment by Urtgard** [comment]
Probably the horde quest. Add this quest too.
