### ISSUE TITLE
Master Calligrapher- Suggesting quests for criteria already done

### ISSUE THREAD

**Issue by yoshimo** [Urtgard/WQAchievements#68]
It seems that each 

- 	Master of Calligraphy - Circle
- 	Master of Calligraphy - Triangle
- 	Master of Calligraphy - Square

is represented by exactly one quest in one zone
Although i am only missing one, i get the others suggested too.
It seems that in your code all quests fulfill all subcriteria, which looks wrong.

Shouldn't that be more like
```

		-- Circle, Square, Triangle
		{name = "Master Calligrapher", id = 13512, criteriaType = "QUESTS", criteria = 
			{{55340, 55342}, 
			{55264, 55343}, 
			{55341, 55344}}},
```

Horde:

Nazmir 		Horde	Circle		55342
Voldun 		Horde	Square		55343
Zuldazar	        Horde	Triangle	        55344

Alliance:
Circle: Tiragarde Sound, Vigil Hill (57, 62)		55340
Square: Drustvar, Fallhaven (56, 34)			55264
Triangle: Stormsong Valley, Fort Daelin (35, 38)	55341

**Comment by Urtgard** [comment]
Thanks for your detailed report.
When I added this achievement I didn't know the horde ids and I play only alliance myself.
Will update it.
