### ISSUE TITLE
Sabertron Assemble: Possible improvement

### ISSUE THREAD

**Issue by yoshimo** [Urtgard/WQAchievements#70]
So we have  multiple colors and multiple quests and multiple npc ids

139328 Red Sabertron No Sabertron world quest up (possible tracking quest 55626)
139335 Yellow	51977
139356 Orange	51978
139336 Green	51976
139359 Copper	51974

51947 unknown color

This is the theory on wowhead comments which i think would be worth trying out

**Comment by Urtgard** [comment]
Tracking for Sabertron Assemble is already added.

Do you've a problem with the tracking?

**Comment by yoshimo** [comment]
I am not familiar with the code but it seems that it throws all quests in together instead of separating quests per criteria

**Comment by Urtgard** [comment]
Maybe these examples help:

`{name = "Sabertron Assemble", id = 13054, criteriaType = "QUESTS", criteria = {nil, 51977, 51978, 51976, 51974}},`

Yellow sabertron is the 2nd achievement criteria. If you miss this criteria we look at the 2nd entry (Lua tables start at 1) in the cirteria table. cirteria[2] = 51977 so we check whether this id is active.

For Master Calligrapher it's the same.
`			{name = "Master Calligrapher", id = 13512, criteriaType = "QUESTS", criteria = {{55340, 55342}, {55264, 55343}, {55341, 55344}}}`
Circle is the 1st achievement criteria. If you miss this criteria we look at the 1st entry in the criteria table. criteria[1] = {55340, 55342} so we check whether 55340 or 55342 is active.

**Comment by yoshimo** [comment]
So you only need the additional brackets for an "or"

**Comment by Urtgard** [comment]
Yes. For the legion fishing achievement it's mixed for example.

`{name = "Fishing \'Round the Isles", id = 10598, criteriaType = "QUESTS", criteria = {
				{41612, 41613, 41270},
				41267,
				{41604, 41605, 41279},
				{41598, 41599, 41264},
				41268,
				41252,
				{41611, 41265, 41610},
				{41617, 41280, 41616},
				{41597, 41244, 41596},
				{41602, 41274, 41603},
				{41609, 41243},
				41273,
				41266,
				{41615, 41275, 41614},
				41278,
				41271,
				41277,
				41240,
				{41269, 41600, 41601},
				41253,
				41276,
				41272,
				41282,
				41283,}
			},`
