### ISSUE TITLE
Hitch when looting in 8.3

### ISSUE THREAD

**Issue by doug-w** [Urtgard/WQAchievements#71]
If WQAchievements is enabled there's a hitch that grows over a session when an inventory item is added to your inventory.  The easiest way to see it is to mail a bunch of items from a different character, open the mailbox and hold down a turn key so you're spinning in place.  As you take each item out of your mailbox there's a hitch that is only present when WQAAchievements is loaded.

**Comment by Urtgard** [comment]
Weird. WQA does nothing with mail, looting and your bags.

Were you active before 8.3?
Does this happen if WQA is the only actice addon?

I'll take a look.

**Comment by Urtgard** [comment]
Couldn't reproduce
