### ISSUE TITLE
Gold reward not working

### ISSUE THREAD

**Issue by dsandrini** [Urtgard/WQAchievements#74]
If I check the _Gold_ option (_Reward_ tab => _General_ menu => _Gold_) and set an amount to be notified when there is a WQ that reward more that X gold, the addon stop to return any quest.
I rolled back to v 2.5 and it works.
I resetted profile and checked only the Gold option from a clean install of the addon.
v.8.3 gold option not working (and if checked no more quest are notified).
v.8.2.5 gold option work

**Comment by Urtgard** [comment]
Thanks for the info and testing older versions.

Does it work if you complete the invasions (fill the bar and kill miniboss quest) in Uldum and the Vale?
I only added the two new zones in v8.3 and my first guess is, that the invasion quest is technically a world quest. But a little bit different and therefore breaks some stuff.

**Comment by dsandrini** [comment]
Hi, I just tryed with the new version on a character that completed both major and minor assault, but still I have the same issue: if I check the _Gold_ option I see no more WQ notifications both in popup and in the chat.

**Comment by Urtgard** [comment]
Fixed in the new version.
