### ISSUE TITLE
Some missing WQs

### ISSUE THREAD

**Issue by strickland** [Urtgard/WQAchievements#75]
There are some legion WQs which are assosiated with spawning rares which is required for some certain achievements.

One example is,

Jed'hin Champion Vorusk which is required for a rare achievement. [Adventurer of Argus] 

Another example is, 

Whiplash in Stormsong Valley. which is again required for the rare achievement in that zone, this isn't legion but I'm only guessing here, maybe there are plenty more of rare elites that are only activated during WQs which are needed for acheivements.

**Comment by strickland** [comment]
Oh also, Zul'tan the Numerous in Argus.

**Comment by Urtgard** [comment]
The [Adventurer of Argus] achievement isn't part of WQA. If you want to help adding it read this: https://www.curseforge.com/wow/addons/wqachievements?page=7#c49

The settings for whiplash seems correct, if you still need him it should work. I'll check it again, if the wq is active.
