### ISSUE TITLE
Filter WQ types

### ISSUE THREAD

**Issue by GijsGoudzwaard** [Urtgard/WQAchievements#79]
Would be nice if we could filter certain world quests. For instance I don't do the pet battle world quests. Would be nice if I could filter all the pet battle world quest achievements

**Comment by Larzous** [comment]
So, I was trying to filter out the achievements that require pets.  But it looks like this is the 'rewards' and filters out the things that GRANT you pets.  We deff need a way to filter out the 'I don't want to do pet battle' ones.
![pets](https://user-images.githubusercontent.com/68357365/87610640-e1fbdc00-c6d3-11ea-9811-9cf3979ab0c3.PNG)
![pets2](https://user-images.githubusercontent.com/68357365/87610721-20919680-c6d4-11ea-8707-661f9006e333.PNG)

**Comment by Urtgard** [comment]
That's the correct setting. It was just bugged.
