### ISSUE TITLE
Found error in 9.0.1-2 preventing it from functioning

### ISSUE THREAD

**Issue by dblanch369** [Urtgard/WQAchievements#87]
Getting this LUA error when trying to access WQA in the brand new version today. (Thanks for getting this worked on!)

10x WQAchievements\WQAchievements-v9.0.1-2release.lua:2328: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: in function `ipairs'
[string "@WQAchievements\WQAchievements-v9.0.1-2release.lua"]:2328: in function `EmissaryReward'
[string "@WQAchievements\WQAchievements-v9.0.1-2release.lua"]:743: in function `CreateQuestList'
[string "@WQAchievements\WQAchievements-v9.0.1-2release.lua"]:1010: in function `?'
[string "@DataStore\libs\AceTimer-3.0\AceTimer-3.0-17.lua"]:55: in function <DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by Urtgard** [comment]
Please try 9.0.1-3
