### ISSUE TITLE
Searching for specific item reward

### ISSUE THREAD

**Issue by NLZ** [Urtgard/WQAchievements#9]
Havent played beta but I read that WQ rewards are randomized:
https://www.wowhead.com/guides/battle-for-azeroth-world-quests#world-quest-rewards
So if there is some OP trinket (like how Shockbaton was nice early on) it could be a reward for any WQ, so it might be worthy to have custom filters without specifying the WQ.
On the other hand, it also says WQ rewards are from dungeon loot tables, so it might be unnecessary as one can get higher ilvl there.

**Comment by Urtgard** [comment]
Yes, searching for a specific reward by itemID in the making.
