### ISSUE TITLE
attempt to perform arithmetic on local 'itemLevel' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [Urtgard/WQAchievements#91]
After the update to 9.0.2 I'm getting the following error when I log into the game. Thanks.
1x WQAchievements\WQAchievements-v9.0.1-4release.lua:2158: attempt to perform arithmetic on local 'itemLevel' (a nil value)
[string "@WQAchievements\WQAchievements-v9.0.1-4release.lua"]:2158: in function `CheckItems'
[string "@WQAchievements\WQAchievements-v9.0.1-4release.lua"]:1913: in function `Reward'
[string "@WQAchievements\WQAchievements-v9.0.1-4release.lua"]:447: in function <WQAchievements\WQAchievements.lua:413>

Locals:
self = <table> {
 watched = <table> {
 }
 IsQuestFlaggedCompleted = <function> defined @WQAchievements\WQAchievements.lua:3229
 UpdateCustomRewards = <function> defined @WQAchievements\Options.lua:1497
 SetRewardLinkByID = <function> defined @WQAchievements\WQAchievements.lua:2848
 EnableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetRewardForID = <function> defined @WQAchievements\WQAchievements.lua:1581
 IterateEmbeds = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 ToggleGet = <function> defined @WQAchievements\Options.lua:1281
 CreateCustomQuest = <function> defined @WQAchievements\Options.lua:1368
 debug = false
 isQuestPinActive = <function> defined @WQAchievements\WQAchievements.lua:3218
 slash = <function> defined @WQAchievements\WQAchievements.lua:467
 SetDefaultModulePrototype = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 Show = <function> defined @WQAchievements\WQAchievements.lua:1428
 emissaryRewards = false
 defaultModuleState = true
 AnnouncePopUp = <function> defined @WQAchievements\WQAchievements.lua:2708
 IsEnabled = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 ExpansionList = <table> {
 }
 ScheduleTimer = <function> defined @DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 missionList = <table> {
 }
 CreateCustomMissionReward = <function> defined @WQAchievements\Options.lua:1627
 GetArgs = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 data = <table> {
 }
 CreateGroup = <function> defined @WQAchievements\Options.lua:1284
 questList = <table> {
 }
 ZoneIDList = <table> {
 }
 start = 390925.180000
 EmissaryReward = <function> defined @WQAchievements\WQAchievements.lua:2947
 questPinMapList = <table> {
 }
 AddRewardToMission = <function> defined @WQAchievements\WQAchievements.lua:1340
 CreateCustomReward = <function> defined @WQAchievements\Options.lua:1486
 SetEnabledState = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 IsTransmogable = <function> defined @WQAchievements\WQAchievements.lua:1986
 enabledState = true
 link = <function> defined @WQAchievements\WQAchievements.lua:1567
 playerName = "Celandine-Cenarius"
 rewards = false
 questPinList = <table> {
 }
 links = <table> {
 }
 event = <unnamed> {
 }
 IterateModules = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 optionsFrame = <unnamed> {
 }
 faction = "Alliance"
 db = <table> {
 }
 baseName = "WQAchievements"
 SortOptions = <function> defined @WQAchievements\Options.lua:1689
 Reward = <function> defined @WQAchievements\WQAchievements.lua:1842
 CancelTimer = <function> defined @DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:147
 CheckWQ = <function> defined @WQAchievements\WQAchievements.lua:1439
 AddToys = <function> defined @WQAchievements\WQAchievements.lua:1285
 AddMounts = <function> defined @WQAchievements\WQAchievements.lua:1220
 OnInitialize = <function> defined @WQAchievements\WQAchievements.lua:276
 NewModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 Disable = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 CreateQTip = <function> defined @WQAchievements\WQAchievements.lua:2419
 AddPets = <function> defined @WQAchievements\WQAchievements.lua:1248
 GetModule = <function> defined @Inte

**Comment by Torsin** [comment]
This appears to be happening on first login and seems like it is trying to get info before it is able, slotID is null as well.  The problem is that prior to line 2158 there is no check to determine if itemLevel is null or not.  Simply adding an if statement just prior to the usage seems to resolve it, from line 2157 in WQAchievements.lua:

```lua
				local itemLevelEquipped = math.min(itemLevel1 or 1000, itemLevel2 or 1000)
				if itemLevel then
					if itemLevel - itemLevelEquipped >= self.db.profile.options.reward.gear.itemLevelUpgradeMin then
						local item = {itemLink = itemLink, itemLevelUpgrade = itemLevel - itemLevelEquipped}
						self:AddRewardToQuest(questID, "ITEM", item, isEmissary)
					end
				end
			end

			-- Azerite Armor Cache
```

**Comment by Ookami313** [comment]
Thanks for the code changes, but it doesn't look like that resolved the issue as I'm still getting an error when logging in. Same basic itemLevel nil value error, but now affecting different lines of code.

5x WQAchievements\WQAchievements-v9.0.1-4release.lua:2177: attempt to perform arithmetic on local 'itemLevel' (a nil value)
[string "@WQAchievements\WQAchievements-v9.0.1-4release.lua"]:2177: in function `CheckItems'
[string "@WQAchievements\WQAchievements-v9.0.1-4release.lua"]:1913: in function `?'
[string "@DataStore\libs\AceTimer-3.0\AceTimer-3.0-17.lua"]:55: in function <DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:
self = <table> {
 watched = <table> {
 }
 IsQuestFlaggedCompleted = <function> defined @WQAchievements\WQAchievements.lua:3231
 UpdateCustomRewards = <function> defined @WQAchievements\Options.lua:1497
 SetRewardLinkByID = <function> defined @WQAchievements\WQAchievements.lua:2850
 EnableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetRewardForID = <function> defined @WQAchievements\WQAchievements.lua:1581
 IterateEmbeds = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 ToggleGet = <function> defined @WQAchievements\Options.lua:1281
 CreateCustomQuest = <function> defined @WQAchievements\Options.lua:1368
 debug = false
 isQuestPinActive = <function> defined @WQAchievements\WQAchievements.lua:3220
 slash = <function> defined @WQAchievements\WQAchievements.lua:467
 SetDefaultModulePrototype = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 Show = <function> defined @WQAchievements\WQAchievements.lua:1428
 emissaryRewards = true
 defaultModuleState = true
 AnnouncePopUp = <function> defined @WQAchievements\WQAchievements.lua:2710
 IsEnabled = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 ExpansionList = <table> {
 }
 ScheduleTimer = <function> defined @DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 missionList = <table> {
 }
 CreateCustomMissionReward = <function> defined @WQAchievements\Options.lua:1627
 GetArgs = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 data = <table> {
 }
 CreateGroup = <function> defined @WQAchievements\Options.lua:1284
 questList = <table> {
 }
 ZoneIDList = <table> {
 }
 start = 6113.999000
 EmissaryReward = <function> defined @WQAchievements\WQAchievements.lua:2949
 questPinMapList = <table> {
 }
 AddRewardToMission = <function> defined @WQAchievements\WQAchievements.lua:1340
 CreateCustomReward = <function> defined @WQAchievements\Options.lua:1486
 SetEnabledState = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 IsTransmogable = <function> defined @WQAchievements\WQAchievements.lua:1986
 enabledState = true
 link = <function> defined @WQAchievements\WQAchievements.lua:1567
 playerName = "Celandine-Cenarius"
 rewards = false
 questPinList = <table> {
 }
 links = <table> {
 }
 event = <unnamed> {
 }
 IterateModules = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 optionsFrame = <unnamed> {
 }
 faction = "Alliance"
 db = <table> {
 }
 baseName = "WQAchievements"
 SortOptions = <function> defined @WQAchievements\Options.lua:1689
 Reward = <function> defined @WQAchievements\WQAchievements.lua:1842
 CancelTimer = <function> defined @DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:147
 CheckWQ = <function> defined @WQAchievements\WQAchievements.lua:1439
 AddToys = <function> defined @WQAchievements\WQAchievements.lua:1285
 AddMounts = <function> defined @WQAchievements\WQAchievements.lua:1220
 OnInitialize = <function> defined @WQAchievements\WQAchievements.lua:276
 NewModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 Disable = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 CreateQTip = <function> defined @WQAchievements\WQAchievements.lua:2421
 AddPets = <function> defined @WQAchievements\WQAchievements.lua:1248
 GetModule = <function> defined @Interfa

**Comment by Torsin** [comment]
Same basic thing, on line 2177 itemLevel is used, on the line just prior to that you should see:
```lua
if itemLevel1 then
```

simply change that to:
```lua
if itemLevel1 and itemLevel then
```

**Comment by Ookami313** [comment]
That looks to have fixed the issue, at least there is no error when logging in. Thanks for the help.

**Comment by Angryaboutelves** [comment]
After performing the two changes mentioned, I get "\WQAchievements-v9.0.1-4release.lua:2278: attempt to perform arithmetic on local 'itemLevel' (a nil value)", which is the same thing only at a different line. 

Why is itemLevel a nil value? It looks like it comes from "itemLevel = GetDetailedItemLevelInfo(itemLink)". Did something change with GetDetailedItemLevelInfo?

**Comment by Ookami313** [comment]
As listed by Angryaboutelves. Not sure what changed, but for the last few days no errors were occurring. As of logging in today, I'm getting the same error.

1x WQAchievements\WQAchievements-v9.0.1-4release.lua:2278: attempt to perform arithmetic on local 'itemLevel' (a nil value)
[string "@WQAchievements\WQAchievements-v9.0.1-4release.lua"]:2278: in function `CheckItems'
[string "@WQAchievements\WQAchievements-v9.0.1-4release.lua"]:1913: in function `?'
[string "@DataStore\libs\AceTimer-3.0\AceTimer-3.0-17.lua"]:55: in function <DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:
self = <table> {
 watched = <table> {
 }
 IsQuestFlaggedCompleted = <function> defined @WQAchievements\WQAchievements.lua:3231
 UpdateCustomRewards = <function> defined @WQAchievements\Options.lua:1497
 SetRewardLinkByID = <function> defined @WQAchievements\WQAchievements.lua:2850
 EnableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetRewardForID = <function> defined @WQAchievements\WQAchievements.lua:1581
 IterateEmbeds = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 ToggleGet = <function> defined @WQAchievements\Options.lua:1281
 CreateCustomQuest = <function> defined @WQAchievements\Options.lua:1368
 debug = false
 isQuestPinActive = <function> defined @WQAchievements\WQAchievements.lua:3220
 slash = <function> defined @WQAchievements\WQAchievements.lua:467
 SetDefaultModulePrototype = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 Show = <function> defined @WQAchievements\WQAchievements.lua:1428
 emissaryRewards = false
 defaultModuleState = true
 AnnouncePopUp = <function> defined @WQAchievements\WQAchievements.lua:2710
 IsEnabled = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 ExpansionList = <table> {
 }
 ScheduleTimer = <function> defined @DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 missionList = <table> {
 }
 CreateCustomMissionReward = <function> defined @WQAchievements\Options.lua:1627
 GetArgs = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 data = <table> {
 }
 CreateGroup = <function> defined @WQAchievements\Options.lua:1284
 questList = <table> {
 }
 ZoneIDList = <table> {
 }
 start = 170467.020000
 EmissaryReward = <function> defined @WQAchievements\WQAchievements.lua:2949
 questPinMapList = <table> {
 }
 AddRewardToMission = <function> defined @WQAchievements\WQAchievements.lua:1340
 CreateCustomReward = <function> defined @WQAchievements\Options.lua:1486
 SetEnabledState = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 IsTransmogable = <function> defined @WQAchievements\WQAchievements.lua:1986
 enabledState = true
 link = <function> defined @WQAchievements\WQAchievements.lua:1567
 playerName = "Celandine-Cenarius"
 rewards = false
 questPinList = <table> {
 }
 links = <table> {
 }
 event = <unnamed> {
 }
 IterateModules = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 optionsFrame = <unnamed> {
 }
 faction = "Alliance"
 db = <table> {
 }
 baseName = "WQAchievements"
 SortOptions = <function> defined @WQAchievements\Options.lua:1689
 Reward = <function> defined @WQAchievements\WQAchievements.lua:1842
 CancelTimer = <function> defined @DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:147
 CheckWQ = <function> defined @WQAchievements\WQAchievements.lua:1439
 AddToys = <function> defined @WQAchievements\WQAchievements.lua:1285
 AddMounts = <function> defined @WQAchievements\WQAchievements.lua:1220
 OnInitialize = <function> defined @WQAchievements\WQAchievements.lua:276
 NewModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 Disable = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 CreateQTip = <function> defined @WQAchievements\WQAchievements.lua:2421
 AddPets = <function> defined @WQAchievements\WQAchievements.lua:1248
 GetModule = <function> defined @Inte

**Comment by Urtgard** [comment]
Before the itemLevel stuff that throws the error I check if itemLink exists.
I noticed that sometimes the itemLink exists, but it's an empty one.
GetDetailedItemLevelInfo returns nothing if the input isn't a proper itemlink, therefore itemLevel is nil and we get the error.

I couldn't test this well, because I couldn't reliably recreate the error.

Let me know if you still get this error.
