### ISSUE TITLE
Impressing Zo'Sorg - PVP WQ from Shadowlands

### ISSUE THREAD

**Issue by tharax** [Urtgard/WQAchievements#96]
[Impressing Zo'Sorg](https://www.wowhead.com/achievement=14516) is a Meta-Achievement for completing each Shadowlands PVP World Quest 20 times. Would be good to have it in the list, like you do for Legion PVP World Quests.

**Comment by Urtgard** [comment]
Finally I added the achievement. If you still need it, keep in mind that you can't always see whether the quest is active and therefore the tracking isn't 100% reliable.
